### ISSUE TITLE
Error during simulate (with sample strategy)

### ISSUE THREAD

**Issue by macracanta** [cunarist/solie#110]
Traceback (most recent call last):
  File "C:\Users\carda\Documents\solie_mod\solie\package\solie\worker\simulator.py", line 670, in simulate_only_visible
    await self.calculate(only_visible=True)
  File "C:\Users\carda\Documents\solie_mod\solie\package\solie\worker\simulator.py", line 1055, in calculate
    calculation_output_data = await gathered
  File "C:\Users\carda\Documents\solie_mod\solie\package\solie\worker\simulator.py", line 1035, in <genexpr>
    gathered = asyncio.gather(
RuntimeError: Task got bad yield: <coroutine object go at 0x000001831C710890>

**Comment by macracanta** [comment]
C:\Python310\lib\asyncio\events.py:80: RuntimeWarning: coroutine 'Collector.download_fill_candle_data.<locals>.download_fill' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
